# Generated by Django 3.2 on 2021-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcumuladoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('casosConfirmados', models.PositiveIntegerField(help_text='Casos confirmados')),
                ('casosDescartados', models.PositiveIntegerField(help_text='Casos descartados')),
                ('casosAguardandoResultado', models.PositiveIntegerField(help_text='Casos aguardando resultados')),
                ('casosSuspeitosInternados', models.PositiveIntegerField(help_text='Casos suspeitos internados')),
                ('obitosConfirmados', models.PositiveIntegerField(help_text='Óbitos confirmados')),
                ('obitosSuspeitos', models.PositiveIntegerField(help_text='Óbtidos suspeitos de COVID-19')),
            ],
            options={
                'verbose_name': 'acumulado diário',
                'verbose_name_plural': 'acumulados diários',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='acumuladodiario',
            index=models.Index(fields=['data'], name='cases_acumu_data_ef2cf2_idx'),
        ),
    ]
