# Generated by Django 3.2 on 2021-04-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumuladodiario',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
